@include('layouts.includes.header-link')
@include('layouts.includes.header')
@include('layouts.includes.nav-bar')
@include('layouts.includes.sidebar')
@yield('mainContent')
@include('layouts.includes.footer')
@include('layouts.includes.footer-script')